default_context:
    full_name: X Author Name
    email: x-pt@example.com
    github_username: x-pt
    project_name: Example Cxx
    project_slug: example-cxx
    package_name: example_cxx
    project_desc: A nice example project

    # C++
    cxx_cmake_version: 3.28
    cxx_standard_version: 20
    cxx_standard_required: true
    cxx_extensions_required: false
    cxx_project_type: [ "binary", "library" ]
    cxx_share_enabled: false
