version: Compose specification

service:
    {{cookiecutter.project_slug}}:
        build: .

networks:
    {{cookiecutter.project_slug}}-net:
        name: {{cookiecutter.project_slug}}-net
        ipam:
            config:
                -   subnet: 172.16.238.0/24
