version: Compose specification

service:
    {{project-name | replace: '-', '_'}}:
        build: .

networks:
    {{project-name | replace: '-', '_'}}-net:
        name: {{project-name | replace: '-', '_'}}-net
        ipam:
            config:
                -   subnet: 172.16.238.0/24
