name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

{% raw  %}
jobs:
    build-and-test:
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Build
                run: make build

            -   name: Test
                run: make run
{% endraw  %}
