name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        name: ${{ matrix.toolchain }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                toolchain:
                    - linux-gcc
                    - windows-msvc
                    - macos-clang
                include:
                    -   toolchain: linux-gcc
                        os: ubuntu-latest
                        compiler: gcc
                    -   toolchain: windows-msvc
                        os: windows-latest
                        compiler: msvc
                    -   toolchain: macos-clang
                        os: macos-latest
                        compiler: clang

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Build
                run: make build

            -   name: Test
                run: make run
