[template]
cargo_generate_version = ">=0.10.0"

[placeholders.gh_uname]
type = "string"
prompt = "GitHub username (or organization)?"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.proj_desc]
type = "string"
prompt = "Project description?"

[placeholders.go_version]
type = "string"
prompt = "Go version? e.g. 1.18, 1.21"
regex = "^[0-9]+(\\.[0-9]+){0,2}$"
