version: Compose specification

service:
    {{cookiecutter.package_name}}:
        build: .

networks:
    {{cookiecutter.package_name}}-net:
        name: {{cookiecutter.package_name}}-net
        ipam:
            config:
                -   subnet: 172.16.238.0/24
