name: Synchronize the example with the template
on:
  push:
    branches: [ main ]

jobs:
  synchronize_example:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: cxx-gh-example
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cargo generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: template
          template_values_file: .github/workflows/template_values.toml

      - name: Checkout old example
        uses: actions/checkout@v3
        with:
          repository: cxx-gh/cxx-gh-example
          path: old_example
          ssh-key: ${{ secrets.GH_EXAMPLE_DEPLOY_SECRET }}

      - name: move sources, mit license and CMakeLists.txt from old to new example
        run: |
          echo "pwd:"
          pwd
          echo "ls -al:"
          ls -al
          rm cxx-gh-example/src/main.cpp
          rm cxx-gh-example/CMakeLists.txt
          rm cxx-gh-example/LICENSE-MIT
          cp old_example/src/* cxx-gh-example/src/
          cp old_example/CMakeLists.txt cxx-gh-example/CMakeLists.txt
          cp old_example/LICENSE-MIT cxx-gh-example/LICENSE-MIT
      - name: update example
        run: |
          mkdir old_sources
          mv old_example/src/* old_sources
          cd old_example
          rm -rf * .gitignore .github/
          echo "ls ../cxx-gh-example:"
          ls ../cxx-gh-example
          echo "ls ../cxx-gh-example/src:"
          ls ../cxx-gh-example/src
          mv ../cxx-gh-example/* ../cxx-gh-example/.github ../cxx-gh-example/.gitignore .
          echo "ls -al:"
          ls -al
          rm src/*
          mv ../old_sources/* src
      - name: commit example
        run: |
          cd old_example
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "automatic update" -m "from $GITHUB_REPOSITORY@$GITHUB_SHA"
            git push
          else
            echo "nothing to commit";
          fi
