name: Synchronize the example with the template
on:
    push:
        branches: [ main ]

jobs:
    synchronize_example:
        runs-on: ubuntu-latest
        env:
            PROJECT_NAME: cxx-gh-example
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run cargo generate
                uses: cargo-generate/cargo-generate-action@v0.16.0
                with:
                    name: ${{ env.PROJECT_NAME }}
                    subfolder: template
                    template_values_file: .github/workflows/template_values.toml

            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v3
                with:
                    deploy_key: ${{ secrets.GH_EXAMPLE_DEPLOY_SECRET }}
                    external_repository: cxx-gh/${{ env.PROJECT_NAME }}
                    publish_branch: main
                    publish_dir: ./${{ env.PROJECT_NAME }}
                    # Set exclude_assets to empty for including the .github directory to deployment assets.
                    exclude_assets: ''
                    enable_jekyll: false
                    user_name: 'github-actions[bot]'
                    user_email: 'github-actions[bot]@users.noreply.github.com'
                    full_commit_message: ${{ github.event.head_commit.message }}
                    force_orphan: true
